version: '3.7'
services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
 
  app:
    build: .
    command: sh -c "rm -f /sfhelpdesk/tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sfhelpdesk
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/sfhelpdesk_development      
    stdin_open: true
    tty: true